import { z } from "zod";

const taggedPostSchema = z.object({
  id: z.number(),
  img_url: z.string().url(),
  caption: z.string().nullable(),
  tagger: z.string(),
  created_at: z.string().optional(), // Auto-generated by backend
});

const taggedPostsSchema = z.array(taggedPostSchema);

type TaggedPost = z.infer<typeof taggedPostSchema>;

export { taggedPostSchema, taggedPostsSchema };
export type { TaggedPost };
